alias ls="ls --color=auto"
alias ll="ls -l"
alias la="ls -la"
alias "cd.."="cd .."
alias "cd..."="cd ../.."
alias "cd...."="cd ../../.."

# Git Aliases
alias g="git"
alias gst="git status"
alias ga="git add"
alias gaa="git add --all"
alias gcmsg="git commit -m"
alias gco="git checkout"
alias gcb="git checkout -b"
alias gl="git pull"
alias gp="git push"
alias gd="git diff"
alias glg="git log --stat"
alias glog="git log --oneline --decorate --graph"

# Docker / Docker Compose Aliases
alias dco="docker compose"
alias dcupd="docker compose up -d"
alias dcdn="docker compose down"
alias dcl="docker compose logs"
alias dclf="docker compose logs -f"
alias dps="docker ps"
alias dpa="docker ps -a"
alias di="docker images"
alias dex="docker exec -it"