#!/usr/bin/env zsh
# shellcheck shell=bash

# Unused variables are intentional for configuration purposes, so we disable the warning for unused variables.
# shellcheck disable=SC2034

LHZSH_CONFIG_DIR=$(realpath ~/.lhzsh)
LHZSH_PLUGINS_DIR="$LHZSH_CONFIG_DIR/plugins"

# Temporarily disable job notifications.
unsetopt monitor

term_greeting(){
    echo ""
    fastfetch -c "$LHZSH_CONFIG_DIR/fastfetch.jsonc"
    echo ""
}


# Check if Fastfetch is available and start it in the background if the shell is interactive
if [[ -o interactive ]] && command -v fastfetch &> /dev/null; then
    term_greeting &
fi

# History
HISTFILE=$LHZSH_CONFIG_DIR/data/history
HISTSIZE=2000
SAVEHIST=2000

setopt autocd notify         # Change directory without cd, report status of background jobs immediately
setopt EXTENDED_HISTORY      # Save timestamps in history
setopt HIST_IGNORE_DUPS      # Do not record an event that was just recorded again
setopt HIST_IGNORE_SPACE     # Do not record an event starting with a space
setopt HIST_EXPIRE_DUPS_FIRST # Delete duplicates first when HISTFILE size exceeds HISTSIZE
setopt SHARE_HISTORY         # Share history between all sessions
setopt HIST_VERIFY           # Do not execute immediately upon history expansion

bindkey -e

zstyle :compinstall filename "$LHZSH_CONFIG_DIR/data/completions"

autoload -Uz compinit && compinit

setopt CORRECT               # Tippfehler-Korrektur vorschlagen

setopt MENU_COMPLETE         # erstes Match sofort einsetzen
setopt AUTO_LIST             # Optionen automatisch listen

zstyle ':completion:*' menu select          # navigierbare Completion-Liste
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'  # case-insensitive
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"  # Farben in Completion

# Advanced Autocompletion styling
zstyle ':completion:*' group-name ''
zstyle ':completion:*:descriptions' format '%F{blue}-- %d --%f'
zstyle ':completion:*:messages' format '%F{purple}-- %d --%f'
zstyle ':completion:*:warnings' format '%F{red}-- no matches found --%f'

setopt INTERACTIVE_COMMENTS


for f in "$LHZSH_PLUGINS_DIR"/**/*.plugin.zsh(N); do
    source "$f"
done

# Enable Custom Theme
source "$LHZSH_CONFIG_DIR/theme.zsh"

# Line Editing Keybindings (Ctrl+Arrows, Ctrl+Backspace, Ctrl+Delete)
bindkey '^[[1;5D' backward-word      # Ctrl+Left
bindkey '^[[1;5C' forward-word       # Ctrl+Right
bindkey '^H' backward-kill-word      # Ctrl+Backspace
bindkey '^W' backward-kill-word      # Ctrl+W
bindkey '^[[3;5~' kill-word          # Ctrl+Delete
bindkey '^[[Z' reverse-menu-complete # Shift-Tab

# History Substring Search Keybindings
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

source "$LHZSH_CONFIG_DIR/alias.zsh"

# Initialize zoxide if installed
if command -v zoxide &> /dev/null; then
    export _ZO_DATA_DIR="$LHZSH_CONFIG_DIR/data/zoxide"
    eval "$(zoxide init zsh --cmd cd)"
fi

# Wait for background jobs to finish before showing the prompt
wait

setopt monitor

# Clean up environment and functions
unset -f term_greeting